[package]
name = "romaji_kana_cvt_rust"
version = "1.3.1"
authors = ["yumetodo <yume-wikijp@live.jp>"]
edition = "2018"
license = "BSL-1.0"

[dependencies]
unicode-normalization = "0.1.8"
log = "0.4"

[dev-dependencies]
# simple-logging = "2.0.2"
